import zmq
import logging
import typing
from enum import StrEnum, IntEnum, Enum


# types
JSONSerializable = typing.Union[
    str, int, float, bool, None, 
    typing.Dict[str, typing.Any], 
    typing.List
]
JSON = typing.Dict[str, JSONSerializable]

byte_types = (bytes, bytearray, memoryview)

# decorator constants 
# naming
USE_OBJECT_NAME : str = "USE_OBJECT_NAME"
# state machine
ANY_STATE   : str = "ANY_STATE"
UNSPECIFIED : str = "UNSPECIFIED"
# types


class ResourceTypes(StrEnum):
    """
    Exposed resource types. This repository does not rely on python's internal getattr, setattr and type checking, 
    to expose RPC operations, but rather segrates resource types and operates on them in predefined ways. This is to allow
    addition or removal of resource types which may demand more integration with HTTP.  
    """
    PROPERTY = "PROPERTY"
    ACTION = "ACTION"
    EVENT = "EVENT"
    THING = "THING"
    

class REGEX(StrEnum):
    """common regexes"""

    states = '[A-Za-z_]+[A-Za-z_ 0-9]*'
    url = r'[\-a-zA-Z0-9@:%._\/\+~#=]{1,256}' 


class HTTP_METHODS(StrEnum):
    """currently supported HTTP request methods"""

    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    DELETE = 'DELETE'
    PATCH = 'PATCH'
    # OPTIONS = 'OPTIONS'

http_methods = [member for member in HTTP_METHODS._member_map_]


# Logging 
class LOGLEVEL(IntEnum):
    """``logging.Logger`` log levels"""
    DEBUG    = logging.DEBUG
    INFO     = logging.INFO
    CRITICAL = logging.CRITICAL
    ERROR    = logging.ERROR
    WARN     = logging.WARN
    FATAL    = logging.FATAL


# ZMQ
class ZMQ_TRANSPORTS(StrEnum):
    """
    supported ZMQ transport protocols - TCP, IPC, INPROC

    TCP - needs socket address additional specified like tcp://0.0.0.0:{port}
    IPC - within python, multiprocess applications, can be autogenerated
    INPROC - within python, multithreaded applications, can be autogenerated
    """
    TCP = "TCP"
    IPC = "IPC"
    INPROC = "INPROC"


class HTTPServerTypes(StrEnum):
    "types of HTTP server"

    SYSTEM_HOST = 'SYSTEM_HOST'
    THING_SERVER = 'THING_SERVER'


class ZMQSocketType(IntEnum):
    PAIR = zmq.PAIR
    PUB = zmq.PUB
    SUB = zmq.SUB
    REQ = zmq.REQ
    REP = zmq.REP
    DEALER = zmq.DEALER
    ROUTER = zmq.ROUTER
    PULL = zmq.PULL
    PUSH = zmq.PUSH
    XPUB = zmq.XPUB
    XSUB = zmq.XSUB
    STREAM = zmq.STREAM
    # Add more socket types as needed


ZMQ_EVENT_MAP = {}
for name in dir(zmq):
    if name.startswith('EVENT_'):
        value = getattr(zmq, name)
        ZMQ_EVENT_MAP[value] = name


# Function to get the socket type name from the enum
def get_socket_type_name(socket_type):
    try:
        return ZMQSocketType(socket_type).name
    except ValueError:
        return "UNKNOWN"


class Operations(StrEnum):
    readProperty = 'readProperty'
    writeProperty = 'writeProperty'
    deleteProperty = 'deleteProperty'
    observeProperty = 'observeProperty'
    invokeAction = 'invokeAction'
    subscribeEvent = 'subscribeEvent'
    unsubscribeEvent = 'unsubscribeEvent'


__all__ = [
    HTTP_METHODS.__name__,
    ZMQ_TRANSPORTS.__name__
]